export const textButton = {
	order: "Pre-order",
	buy: "Buy",
	learnMore: "Learn More",
};

export const sectionTitle = {
	title1: "Which iPhone is right for you?",
	title2: "Which MacBook is right for you?",
	title3: "Which iPad is right for you?",
};

export const productsInfo = [
	{
		id: 1,
		title: "Iphone 14 Pro",
		category: "Phone",
		description: "The ultimate iPhone",
		display: '6.7" or 6.1" Super Retina XDR Display, ProMotion Technology, Always-On Display',
		camera: "48Mp Main | Ultra Wide Telephoto (Pro Camera System)",
		chipset: "A16 Bionic",
		network: "Superfast 5G cellular e-sim",
		price: 999,
		condition: "New",
		img: "https://i.imgur.com/25ia4FG.png",
	},
	{
		id: 2,
		title: "Iphone 14",
		category: "Phone",
		description: "A total powerhouse",
		display: '6.7" or 6.1" Super Retina XDR Display',
		camera: "12MP Main | Ultra Wide (Advanced Dual-Camera System)",
		chipset: "A15 Bionic with 5-core GPU",
		network: "Superfast 5G cellular e-sim",
		price: 799,
		condition: "New",
		img: "https://i.imgur.com/DDEuK2p.png",
	},
	{
		id: 3,
		title: "Iphone 13 Pro",
		category: "Phone",
		description: "As amazing as ever",
		display: '6.1" or 5.4" Super Retina XDR Display',
		camera: "12MP Main | Ultra Wide (Dual-Camera System)",
		chipset: "A15 Bionic with 4-core GPU",
		network: "Superfast 5G cellular",
		price: 599,
		condition: "⠀",
		img: "https://i.imgur.com/3v8MevH.png",
	},
	{
		id: 4,
		title: "Iphone SE",
		category: "Phone",
		description: "Serious power. Serious value",
		display: '4.7" Retina HD Display',
		camera: "12MP Main (Advance Camera System)",
		chipset: "A15 Bionic with 4-core GPU",
		network: "5G cellular",
		price: 429,
		condition: "⠀",
		img: "https://i.imgur.com/WSJErze.png",
	},
	{
		id: 5,
		title: "MacBook 16 Pro",
		category: "Computer",
		description: "Supercharged for pros",
		display: '14.2" or 16.2" Liquid Retina XDR Display',
		chipset: "Apple M1 Pro chip or Apple M1 Max chip",
		weight: "3.5lb. or 4.7lb.",
		battery: "Up to 21 hours battery life",
		price: 1999,
		condition: "⠀",
		img: "https://i.imgur.com/Ho9bBbR.png",
	},
	{
		id: 6,
		title: "MacBook 13 Pro",
		category: "Computer",
		description: "Pro anywhere",
		display: '13.3" Retina Display',
		chipset: "Apple M2",
		weight: "3.0lb.",
		battery: "Up to 20 hours battery life",
		price: 1299,
		condition: "New",
		img: "https://i.imgur.com/j3JA5Z3.png",
	},
	{
		id: 7,
		title: "MacBook Air",
		description: "M2 Chip",
		category: "Computer",
		display: '13.6" Liquid Retina Display',
		chipset: "Apple M2 chip",
		weight: "2.7lb.",
		battery: "Up to 18 hours battey life",
		price: 1199,
		condition: "New",
		img: "https://i.imgur.com/Q67Gfta.png",
	},
	{
		id: 8,
		title: "MacBook Air",
		category: "Computer",
		description: "M1 Chip",
		display: '13.3" Retina Display',
		chipset: "Apple M1 chip",
		weight: "2.8lb.",
		battery: "Up to 18 hours battery life",
		price: 999,
		condition: "⠀",
		img: "https://i.imgur.com/H20QUh3.png",
	},
	{
		id: 9,
		title: "Ipad Pro 10",
		category: "Ipad",
		description: "The ultimate iPad experience.",
		display: '12.9" Liquid Retina XDR Display and 11" Liquid Retina Display ',
		camera: "12MP Wide and 10MP ultra Wide Back Cameras",
		chipset: "M1 Chip",
		connectivity: "Works with Apple pencil (2nd Generation), and Magic Keyboard and Smart Keyboard Folio",
		price: 799,
		condition: "⠀",
		img: "https://i.imgur.com/1AUuL9E.png",
	},
	{
		id: 10,
		title: "Ipad Air",
		category: "Ipad",
		description: "Powerfull. Colorfull",
		display: '10.9" Liquid Retina Display',
		camera: "12MP Wide Back Camera",
		chipset: "M1 Chip",
		connectivity: "Works with Apple Pencil (2nd Generation), and Magic Keyboard and Smart Keyboard Folio",
		price: 599,
		condition: "New",
		img: "https://i.imgur.com/x5HNXVW.png",
	},
	{
		id: 11,
		title: "Ipad",
		category: "Ipad",
		description: "Delightfully capable",
		display: '10.2" Retina Display',
		camera: "8MP Wide Back Camera",
		chipset: "A13 Bionic Chip",
		connectivity: "Works with Apple Pencil (1st Generation), and Smart Keyboard",
		price: 329,
		condition: "New",
		img: "https://i.imgur.com/uW3PeMN.png",
	},
	{
		id: 12,
		title: "Ipad Mini",
		category: "Ipad",
		description: "Mega power. Mini sized",
		display: '8.3" Liquid Retina Display',
		camera: "12MP Wide Back Camera",
		chipset: "A15 Bionic Chip",
		connectivity: "Works with Apple Pencil (2nd Generation), and Bluetooth Keyboards",
		price: 499,
		condition: "⠀",
		img: "https://i.imgur.com/gYpWHeL.png",
	},
];

export const cardsInfoIphone = [
	{
		id: 1,
		title: "Iphone 14 Pro",
		description: "The ultimate iPhone",
		price: 999,
		condition: "New",
		img: "https://i.imgur.com/25ia4FG.png",
	},
	{
		id: 2,
		title: "Iphone 14",
		description: "A total powerhouse",
		price: 799,
		condition: "New",
		img: "https://i.imgur.com/DDEuK2p.png",
	},
	{
		id: 3,
		title: "Iphone 13 Pro",
		description: "As amazing as ever",
		price: 599,
		condition: "",
		img: "https://i.imgur.com/3v8MevH.png",
	},
	{
		id: 4,
		title: "Iphone SE",
		description: "Serious power. Serious value",
		price: 429,
		condition: "",
		img: "https://i.imgur.com/WSJErze.png",
	},
];
export const cardsInfoMac = [
	{
		id: 5,
		title: "MacBook 16 Pro",
		description: "Supercharged for pros",
		price: 1999,
		condition: "",
		img: "https://i.imgur.com/Ho9bBbR.png",
	},
	{
		id: 6,
		title: "MacBook 13 Pro",
		description: "Pro anywhere",
		price: 1299,
		condition: "New",
		img: "https://i.imgur.com/j3JA5Z3.png",
	},
	{
		id: 7,
		title: "MacBook Air",
		description: "M2 Chip",
		price: 1199,
		condition: "New",
		img: "https://i.imgur.com/Q67Gfta.png",
	},
	{
		id: 8,
		title: "MacBook Air",
		description: "M1 Chip",
		price: 999,
		condition: "",
		img: "https://i.imgur.com/H20QUh3.png",
	},
];
export const cardsInfoIpad = [
	{
		id: 9,
		title: "Ipad Pro",
		description: "The ultimate iPad experience.",
		price: 799,
		condition: "",
		img: "https://i.imgur.com/1AUuL9E.png",
	},
	{
		id: 10,
		title: "Ipad Air",
		description: "Powerfull. Colorfull",
		price: 599,
		condition: "New",
		img: "https://i.imgur.com/x5HNXVW.png",
	},
	{
		id: 11,
		title: "Ipad",
		description: "Delightfully capable",
		price: 329,
		condition: "New",
		img: "https://i.imgur.com/uW3PeMN.png",
	},
	{
		id: 12,
		title: "Ipad Mini",
		description: "Mega power. Mini sized",
		price: 499,
		condition: "",
		img: "https://i.imgur.com/gYpWHeL.png",
	},
];

export const SliderData = [
	{
		image: "https://i.imgur.com/81wn4AA.jpg",
		id: 1,
	},
	{
		image: "https://i.imgur.com/Dh0C6XS.jpg",
		id: 2,
	},
	{
		image: "https://i.imgur.com/A6Ov5Lz.jpg",
		id: 3,
	},
	{
		image: "https://i.imgur.com/3klcdtD.jpg",
		id: 4,
	},
	{
		image: "https://i.imgur.com/xL6rcDi.jpg",
		id: 5,
	},
	{
		image: "https://i.imgur.com/NatpPLh.jpg",
		id: 6,
	},
	{
		image: "https://i.imgur.com/c6N5mdk.jpg",
		id: 7,
	},
	{
		image: "https://i.imgur.com/EyoH0bi.jpg",
		id: 8,
	},
	{
		image: "https://i.imgur.com/TbID5A7.jpg",
		id: 9,
	},
];

export const SliderDataMobile = [
	{
		image: "https://i.imgur.com/KI1x2xb.jpg",
		id: 1,
	},
	{
		image: "https://i.imgur.com/GE5AFma.jpg",
		id: 2,
	},
	{
		image: "https://i.imgur.com/KlPDZgU.jpg",
		id: 3,
	},
	{
		image: "https://i.imgur.com/3zgnnt4.jpg",
		id: 4,
	},
	{
		image: "https://i.imgur.com/vVc8q9E.jpg",
		id: 5,
	},
	{
		image: "https://i.imgur.com/4TVpCIS.jpg",
		id: 6,
	},
	{
		image: "https://i.imgur.com/gA1j9Yz.jpg",
		id: 7,
	},
	{
		image: "https://i.imgur.com/77S6Dsn.jpg",
		id: 8,
	},
	{
		image: "https://i.imgur.com/3o4NC56.jpg",
		id: 9,
	},
];
