export const textButton = {
	order: "Pre-order",
	buy: "Buy",
	learnMore: "Learn More",
};

export const sectionTitle = {
	title1: "Which iPhone is right for you?",
	title2: "Which MacBook is right for you?",
	title3: "Which iPad is right for you?",
};

export const productsInfo = [
	{
		id: 1,
		title: "iPhone 14 Pro",
		category: "Phone-Order",
		description: "The ultimate iPhone.",
		displaySize: '6.7" or 6.1"',
		displayType: "Super Retina XDR display. ProMotion technology. Always-On display",
		cameraSystem: "Pro camera system",
		cameraType: "48Mp Main | Ultra Wide | Telephoto Autofocus on TrueDepth front camera",
		battery: "Up to 23 hours video playback",
		chipset: "A16 Bionic 6-core GPU",
		recognition: "Face ID",
		network: "Superfast 5G cellular e-sim",
		price: 999,
		condition: "New",
		img: "https://i.imgur.com/25ia4FG.png",
		cameraImg: "https://i.imgur.com/mXTnxtR.png",
		batteryImg: "https://i.imgur.com/ZmEXuSY.png",
		chipsetImg: "https://i.imgur.com/8wOOudM.png",
		recognitionImg: "https://i.imgur.com/WFzwu5x.png",
		networkImg: "https://i.imgur.com/Fim7uv6.png",
	},
	{
		id: 2,
		title: "iPhone 14",
		category: "Phone",
		description: "A total powerhouse.",
		displaySize: '6.7" or 6.1"',
		displayType: "Super Retina XDR display",
		cameraSystem: "Advanced dual-camera system",
		cameraType: "12Mp Main | Ultra Wide Autofocus on TrueDepth front camera",
		battery: "Up to 20 hours video playback",
		chipset: "A15 Bionic 6-core GPU",
		recognition: "Face ID",
		network: "Superfast 5G cellular e-sim",
		price: 799,
		condition: "New",
		img: "https://i.imgur.com/DDEuK2p.png",
		imgModal: "https://i.imgur.com/Xwo9Tv9.jpg",
		cameraImg: "https://i.imgur.com/XQBPufl.png",
		batteryImg: "https://i.imgur.com/ZmEXuSY.png",
		chipsetImg: "https://i.imgur.com/lr9BVNF.png",
		recognitionImg: "https://i.imgur.com/WFzwu5x.png",
		networkImg: "https://i.imgur.com/Fim7uv6.png",
	},
	{
		id: 3,
		title: "iPhone 13",
		category: "Phone",
		description: "As amazing as ever.",
		displaySize: '6.1" or 5.4"',
		displayType: "Super Retina XDR display",
		cameraSystem: "Dual-camera system",
		cameraType: "12Mp Main | Ultra Wide TrueDepth front camera",
		battery: "Up to 19 hours video playback",
		chipset: "A15 Bionic 4-core GPU",
		recognition: "Face ID",
		network: "Superfast 5G cellular",
		price: 599,
		condition: "⠀",
		img: "https://i.imgur.com/3v8MevH.png",
		imgModal: "https://i.imgur.com/Ki2XfD4.jpg",
		cameraImg: "https://i.imgur.com/XQBPufl.png",
		batteryImg: "https://i.imgur.com/ZmEXuSY.png",
		chipsetImg: "https://i.imgur.com/lr9BVNF.png",
		recognitionImg: "https://i.imgur.com/WFzwu5x.png",
		networkImg: "https://i.imgur.com/Fim7uv6.png",
	},
	{
		id: 4,
		title: "iPhone 12",
		category: "Phone",
		description: "Perfect balance.",
		displaySize: '6.1"',
		displayType: "Super Retina XDR display",
		cameraSystem: "Dual-camera system",
		cameraType: "12Mp Main | Ultra Wide TrueDepth front camera",
		battery: "Up to 17 hours video playback",
		chipset: "A14 Bionic 4-core GPU",
		recognition: "Face ID",
		network: "Superfast 5G cellular",
		price: 599,
		condition: "⠀",
		img: "https://i.imgur.com/XdVF7xn.png",
		imgModal: "https://i.imgur.com/G9ADxhY.jpg",
		cameraImg: "https://i.imgur.com/XQBPufl.png",
		batteryImg: "https://i.imgur.com/ZmEXuSY.png",
		chipsetImg: "https://i.imgur.com/VsNU4Il.png",
		recognitionImg: "https://i.imgur.com/WFzwu5x.png",
		networkImg: "https://i.imgur.com/Fim7uv6.png",
	},
	{
		id: 5,
		title: "Iphone SE",
		category: "Phone",
		description: "Serious power. Serious value.",
		displaySize: '4.7"',
		displayType: "Retina HD display",
		cameraSystem: "Single camera",
		cameraType: "12Mp Main Front camera",
		battery: "Up to 13 hours video playback",
		chipset: "A13 Bionic 4-core GPU",
		recognition: "Touch ID",
		network: "4G LTE cellular",
		price: 429,
		condition: "⠀",
		img: "https://i.imgur.com/WSJErze.png",
		imgModal: "https://i.imgur.com/STwenXv.jpg",
		cameraImg: "https://i.imgur.com/DPuKe2c.png",
		batteryImg: "https://i.imgur.com/ZmEXuSY.png",
		chipsetImg: "https://i.imgur.com/cYSYx4I.png",
		recognitionImg: "https://i.imgur.com/nUDM15M.png",
		networkImg: "https://i.imgur.com/SIMxPxK.png",
	},
	{
		id: 6,
		title: "MacBook 16 Pro",
		category: "Computer",
		description: "Supercharged for pros.",
		displaySize: '16.2""',
		displayType: "Liquid Retina XDR display",
		chipset: "Apple M1 Pro chip",
		cpu: "10-core",
		gpu: "32-core",
		ram: "64GB",
		storage: "8TB",
		battery: "21 hours battery life",
		recognition: "Touch ID",
		price: 2499,
		condition: "New",
		img: "https://i.imgur.com/Ho9bBbR.png",
		imgModal: "https://i.imgur.com/Ho9bBbR.png",
		batteryImg: "https://i.imgur.com/ZmEXuSY.png",
		chipsetImg: "https://i.imgur.com/evokUzx.png",
		recognitionImg: "https://i.imgur.com/nUDM15M.png",
	},
	{
		id: 7,
		title: "MacBook 13 Pro",
		category: "Computer",
		description: "Pro anywhere.",
		displaySize: '13.3""',
		displayType: "Retina display",
		chipset: "Apple M2 chip",
		cpu: "8-core",
		gpu: "10-core",
		ram: "24GB",
		storage: "2TB",
		battery: "20 hours battery life",
		recognition: "Touch Bar and Touch ID",
		price: 1299,
		condition: "New",
		img: "https://i.imgur.com/j3JA5Z3.png",
		imgModal: "https://i.imgur.com/j3JA5Z3.png",
		batteryImg: "https://i.imgur.com/ZmEXuSY.png",
		chipsetImg: "https://i.imgur.com/YR5pGNW.png",
		recognitionImg: "https://i.imgur.com/nUDM15M.png",
	},
	{
		id: 8,
		title: "MacBook Air",
		description: "M2 Chip.",
		category: "Computer",
		displaySize: '13.6""',
		displayType: "Liquid Retina display",
		chipset: "Apple M2 chip",
		cpu: "8-core",
		gpu: "10-core",
		ram: "24GB",
		storage: "2TB",
		battery: "18 hours battery life",
		recognition: "Touch ID",
		price: 1199,
		condition: "New",
		img: "https://i.imgur.com/Q67Gfta.png",
		imgModal: "https://i.imgur.com/Q67Gfta.png",
		batteryImg: "https://i.imgur.com/ZmEXuSY.png",
		chipsetImg: "https://i.imgur.com/YR5pGNW.png",
		recognitionImg: "https://i.imgur.com/nUDM15M.png",
	},
	{
		id: 9,
		title: "MacBook Air",
		category: "Computer",
		description: "M1 Chip.",
		displaySize: '13.3""',
		displayType: "Retina display",
		chipset: "Apple M1 chip",
		cpu: "8-core",
		gpu: "7-core",
		ram: "16GB",
		storage: "2TB",
		battery: "18 hours battery life",
		recognition: "Touch ID",
		price: 999,
		condition: "⠀",
		img: "https://i.imgur.com/H20QUh3.png",
		imgModal: "https://i.imgur.com/H20QUh3.png",
		batteryImg: "https://i.imgur.com/ZmEXuSY.png",
		chipsetImg: "https://i.imgur.com/EIm3O2T.png",
		recognitionImg: "https://i.imgur.com/nUDM15M.png",
	},
	{
		id: 10,
		title: "Ipad Pro",
		category: "Ipad",
		description: "The ultimate iPad experience.",
		displaySize: '12.9""',
		displayType: "Liquid Retina XDR display",
		cameraType: "12MP Wide and 10MP ultra Wide cameras",
		chipset: "M1 chip with next-generation Neural Engine",
		storage: "2TB",
		connector: "USB-C connector with support for Thunderbolt / USB 4",
		network: "5G Superfast downloads and streaming",
		price: 1099,
		condition: "⠀",
		img: "https://i.imgur.com/1AUuL9E.png",
		imgModal: "https://i.imgur.com/DWY4SZN.jpg",
		chipsetImg: "https://i.imgur.com/EIm3O2T.png",
		cameraImg: "https://i.imgur.com/AB8E2Vo.png",
		connectorImg: "https://i.imgur.com/8gCNZWy.png",
		networkImg: "https://i.imgur.com/Fim7uv6.png",
	},
	{
		id: 11,
		title: "Ipad Air",
		category: "Ipad",
		description: "Powerfull. Colorfull.",
		displaySize: '10.9""',
		displayType: "Liquid Retina display True Tone",
		cameraType: "12MP Wide camera",
		chipset: "M1 chip with next-generation Neural Engine",
		storage: "256GB",
		connector: "USB-C connector",
		network: "5G Superfast downloads and streaming",
		price: 599,
		condition: "New",
		img: "https://i.imgur.com/x5HNXVW.png",
		imgModal: "https://i.imgur.com/zU9kXA8.jpg",
		chipsetImg: "https://i.imgur.com/EIm3O2T.png",
		cameraImg: "https://i.imgur.com/T6wZfeR.png",
		connectorImg: "https://i.imgur.com/pOnSpn5.png",
		networkImg: "https://i.imgur.com/Fim7uv6.png",
	},
	{
		id: 12,
		title: "Ipad",
		category: "Ipad",
		description: "Delightfully capable.",
		displaySize: '10.2""',
		displayType: "Retina display True Tone",
		cameraType: "8MP Wide camera",
		chipset: "A13 Bionic Chip with Neural Engine",
		storage: "256GB",
		connector: "Lightning connector",
		network: "4G LTE cellular",
		price: 329,
		condition: "New",
		img: "https://i.imgur.com/uW3PeMN.png",
		imgModal: "https://i.imgur.com/wHdWWBW.jpg",
		chipsetImg: "https://i.imgur.com/cYSYx4I.png",
		cameraImg: "https://i.imgur.com/LZV1N3l.png",
		connectorImg: "https://i.imgur.com/Ai2Isb1.png",
		networkImg: "https://i.imgur.com/SIMxPxK.png",
	},
	{
		id: 13,
		title: "Ipad Mini",
		category: "Ipad",
		description: "Mega power. Mini sized.",
		displaySize: '8.3"',
		displayType: "Liquid Retina display True Tone",
		cameraType: "12MP Wide camera",
		chipset: "A15 Bionic Chip with Neural Engine",
		storage: "256GB",
		connector: "USB-C connector",
		network: "5G Superfast downloads and streaming",
		price: 499,
		condition: "⠀",
		img: "https://i.imgur.com/gYpWHeL.png",
		imgModal: "https://i.imgur.com/0fX3OmJ.jpg",
		chipsetImg: "https://i.imgur.com/lr9BVNF.png",
		cameraImg: "https://i.imgur.com/LZV1N3l.png",
		connectorImg: "https://i.imgur.com/pOnSpn5.png",
		networkImg: "https://i.imgur.com/Fim7uv6.png",
	},
];

export const cardsInfoIphone = [
	{
		id: 1,
		title: "Iphone 14 Pro",
		description: "The ultimate iPhone",
		price: 999,
		condition: "New",
		img: "https://i.imgur.com/25ia4FG.png",
	},
	{
		id: 2,
		title: "Iphone 14",
		description: "A total powerhouse",
		price: 799,
		condition: "New",
		img: "https://i.imgur.com/DDEuK2p.png",
	},
	{
		id: 3,
		title: "Iphone 13 Pro",
		description: "As amazing as ever",
		price: 599,
		condition: "",
		img: "https://i.imgur.com/3v8MevH.png",
	},
	{
		id: 4,
		title: "Iphone SE",
		description: "Serious power. Serious value",
		price: 429,
		condition: "",
		img: "https://i.imgur.com/WSJErze.png",
	},
];
export const cardsInfoMac = [
	{
		id: 5,
		title: "MacBook 16 Pro",
		description: "Supercharged for pros",
		price: 1999,
		condition: "",
		img: "https://i.imgur.com/Ho9bBbR.png",
	},
	{
		id: 6,
		title: "MacBook 13 Pro",
		description: "Pro anywhere",
		price: 1299,
		condition: "New",
		img: "https://i.imgur.com/j3JA5Z3.png",
	},
	{
		id: 7,
		title: "MacBook Air",
		description: "M2 Chip",
		price: 1199,
		condition: "New",
		img: "https://i.imgur.com/Q67Gfta.png",
	},
	{
		id: 8,
		title: "MacBook Air",
		description: "M1 Chip",
		price: 999,
		condition: "",
		img: "https://i.imgur.com/H20QUh3.png",
	},
];
export const cardsInfoIpad = [
	{
		id: 9,
		title: "Ipad Pro",
		description: "The ultimate iPad experience.",
		price: 799,
		condition: "",
		img: "https://i.imgur.com/1AUuL9E.png",
	},
	{
		id: 10,
		title: "Ipad Air",
		description: "Powerfull. Colorfull",
		price: 599,
		condition: "New",
		img: "https://i.imgur.com/x5HNXVW.png",
	},
	{
		id: 11,
		title: "Ipad",
		description: "Delightfully capable",
		price: 329,
		condition: "New",
		img: "https://i.imgur.com/uW3PeMN.png",
	},
	{
		id: 12,
		title: "Ipad Mini",
		description: "Mega power. Mini sized",
		price: 499,
		condition: "",
		img: "https://i.imgur.com/gYpWHeL.png",
	},
];

export const SliderData = [
	{
		image: "https://i.imgur.com/81wn4AA.jpg",
		id: 1,
	},
	{
		image: "https://i.imgur.com/Dh0C6XS.jpg",
		id: 2,
	},
	{
		image: "https://i.imgur.com/A6Ov5Lz.jpg",
		id: 3,
	},
	{
		image: "https://i.imgur.com/3klcdtD.jpg",
		id: 4,
	},
	{
		image: "https://i.imgur.com/xL6rcDi.jpg",
		id: 5,
	},
	{
		image: "https://i.imgur.com/NatpPLh.jpg",
		id: 6,
	},
	{
		image: "https://i.imgur.com/c6N5mdk.jpg",
		id: 7,
	},
	{
		image: "https://i.imgur.com/EyoH0bi.jpg",
		id: 8,
	},
	{
		image: "https://i.imgur.com/TbID5A7.jpg",
		id: 9,
	},
];

export const SliderDataMobile = [
	{
		image: "https://i.imgur.com/KI1x2xb.jpg",
		id: 1,
	},
	{
		image: "https://i.imgur.com/GE5AFma.jpg",
		id: 2,
	},
	{
		image: "https://i.imgur.com/KlPDZgU.jpg",
		id: 3,
	},
	{
		image: "https://i.imgur.com/3zgnnt4.jpg",
		id: 4,
	},
	{
		image: "https://i.imgur.com/vVc8q9E.jpg",
		id: 5,
	},
	{
		image: "https://i.imgur.com/4TVpCIS.jpg",
		id: 6,
	},
	{
		image: "https://i.imgur.com/gA1j9Yz.jpg",
		id: 7,
	},
	{
		image: "https://i.imgur.com/77S6Dsn.jpg",
		id: 8,
	},
	{
		image: "https://i.imgur.com/3o4NC56.jpg",
		id: 9,
	},
];
